import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: any) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.journal": "Journal",
    "nav.analysis": "Analyze",
    "nav.settings": "Settings",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "dashboard.welcome": "Welcome back,",
    "dashboard.recent": "Recent Analyses",
    "dashboard.stats": "Your Stats",
    "analysis.title": "Emotion Analysis",
    "analysis.placeholder": "How are you feeling today? Write your thoughts here...",
    "analysis.button": "Analyze Emotion",
    "journal.title": "Your Journal",
    "journal.empty": "No entries yet. Start by analyzing your first thought!",
    "settings.title": "Settings",
    "settings.account_info": "Account Info",
    "settings.edit": "Edit",
    "settings.full_name": "Full Name",
    "settings.language": "Language",
    "settings.app_icon": "App Icon",
    "settings.data_management": "Data Management",
    "settings.export_data": "Export Data",
    "settings.import_data": "Import Data",
    "settings.clear_data": "Clear All Data",
    "settings.danger_zone": "Danger Zone",
    "settings.pin_code": "PIN Code Lock",
    "settings.set_pin": "Set PIN",
    "settings.remove_pin": "Remove PIN",
    "settings.reminder_time": "Daily Reminder",
    "achievements.title": "Achievements",
    "calendar.title": "Emotional Calendar",
    "calendar.add_new": "Add Event",
    "calendar.event_name": "Event Name",
    "calendar.empty": "No events scheduled.",
    "emotions.happy": "Happy",
    "emotions.sad": "Sad",
    "emotions.angry": "Angry",
    "emotions.anxious": "Anxious",
    "emotions.neutral": "Neutral",
    "emotions.excited": "Excited",
    "emotions.calm": "Calm",
    "emotions.frustrated": "Frustrated",
    "journal.entries_count": "entries",
    "journal.filter_by": "Filter by",
    "journal.no_results": "No entries found",
    "achievements.pioneer": "Pioneer",
    "achievements.pioneer_desc": "Analyze your first thought.",
    "achievements.streak_7": "7-Day Streak",
    "achievements.streak_desc": "Keep a streak for 7 days.",
    "achievements.entry_30": "30 Entries",
    "achievements.entry_30_desc": "Reach 30 total entries.",
    "achievements.entry_100": "100 Entries",
    "achievements.entry_100_desc": "Reach 100 total entries.",
    "achievements.locked_desc": "Keep going to unlock this!",
    "achievements.current_streak": "Current Streak",
    "achievements.streak_sub": "Keep writing daily to build your streak!",
    "achievements.unlocked": "Unlocked",
    "settings.reminder_desc": "Get a gentle nudge to write.",
    "settings.privacy": "Privacy & Security",
    "settings.danger_zone_desc": "This action is permanent and cannot be undone. All your history will be lost.",
    "settings.general": "General",
    "settings.appearance": "Appearance",
    "settings.security": "Security",
    "settings.data": "Data",
    "settings.achievements": "Achievements",
    "settings.calendar": "Calendar",
    "settings.profile": "Profile",
    "settings.account": "Account",
    "settings.persona": "AI Persona",
    "settings.persona_desc": "Choose how the AI interacts with you.",
    "settings.theme": "Theme",
    "settings.notifications": "Notifications",
    "settings.reminder": "Daily Reminder",
    "settings.pin_desc": "Secure your thoughts with a 4-digit PIN.",
    "settings.biometrics": "Biometric Unlock",
    "settings.export_desc": "Download all your entries as a JSON file.",
    "settings.edit_profile": "Edit Profile",
    "settings.save_changes": "Save Changes",
    "settings.email_address": "Email Address",
    "settings.change_avatar": "Change Avatar",
    "settings.streak_stats": "Streak Stats",
    "settings.total_entries": "Total Entries",
    "settings.unlocked_achievements": "Unlocked",
    "settings.locked": "Locked",
    "settings.add_event": "Add Event",
    "settings.event_title": "Event Title",
    "settings.event_date": "Event Date",
    "settings.no_events": "No events for this day",
    "settings.your_achievements": "Your Achievements",
    "settings.mental_calendar": "Mental Calendar",
    "settings.voice_input_desc": "Use your voice to record thoughts.",
    "settings.voice_input_enabled": "Voice Input Enabled",
    "settings.voice_input_disabled": "Voice Input Disabled",
    "journal.search_placeholder": "Search thoughts or tags...",
    "journal.all_emotions": "All Emotions",
    "journal.no_results_desc": "Try adjusting your filters or search query.",
    "journal.intensity": "Intensity",
    "journal.details": "Details",
    "analysis.input_source": "Input Source",
    "analysis.stop_recording": "Stop Recording",
    "analysis.voice_input": "Voice Input",
    "analysis.detected_emotion": "Detected Emotion",
    "analysis.confidence": "Confidence",
    "analysis.sentiment": "Sentiment",
    "analysis.recommended_music": "Recommended Music",
    "analysis.advice_title": "Soulful Advice",
    "analysis.start_new": "Start New Analysis",
    "analysis.ready_title": "Ready to analyze?",
    "analysis.ready_desc": "Write your thoughts or use voice input to discover your emotional state.",
    "dashboard.engine_online": "Emotional Engine Online",
    "dashboard.welcome_back": "Welcome back,",
    "dashboard.ready_question": "Ready to dive into your emotions today?",
    "dashboard.new_analysis": "New Analysis",
    "dashboard.streak": "STREAK",
    "dashboard.total": "TOTAL",
    "dashboard.days": "Days",
    "dashboard.keep_it_up": "Keep it up!",
    "dashboard.total_entries": "Total Entries",
    "dashboard.mood": "MOOD",
    "dashboard.dominant_mood": "Dominant Mood",
    "dashboard.level": "LEVEL",
    "dashboard.level_label": "Level",
    "dashboard.to_next": "to next",
    "dashboard.distribution": "Emotional Distribution",
    "dashboard.unlock_desc": "Unlock with 2+ entries",
    "dashboard.correlations": "Smart Correlations",
    "dashboard.correlations_desc": "Use tags in your analysis to unlock correlations.",
    "layout.light_mode": "Light Mode",
    "layout.dark_mode": "Dark Mode",
    "layout.logout": "Logout",
    "sentiment.positive": "Positive",
    "sentiment.negative": "Negative",
    "sentiment.neutral": "Neutral",
    "analysis.error_no_text": "Please enter some text",
    "analysis.error_failed": "Analysis failed. Please try again.",
    "analysis.error_mic": "Microphone not supported",
    "analysis.error_voice": "Voice input error",
    "dashboard.no_data": "No data",
    "settings.user_name": "User",
    "settings.no_email": "No email set",
    "settings.pin_active": "Active & Secure",
    "settings.pin_not_set": "Not set - Add extra protection",
    "auth.login_title": "Emotion Analyzer",
    "auth.login_subtitle": "Sign in to start analyzing emotions",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgot_password": "Forgot password?",
    "auth.sign_in": "Sign In",
    "auth.no_account": "Don't have an account?",
    "auth.sign_up": "Sign up",
    "auth.signup_title": "Create Account",
    "auth.signup_subtitle": "Start your emotional journey today",
    "auth.full_name": "Full Name",
    "auth.confirm_password": "Confirm Password",
    "auth.have_account": "Already have an account?",
    "auth.forgot_title": "Forgot Password",
    "auth.forgot_subtitle": "Enter your email to reset your password",
    "auth.send_reset": "Send Reset Link",
    "auth.back_to_login": "Back to login",
    "auth.reset_title": "Reset Password",
    "auth.reset_subtitle": "Enter your new password below",
    "auth.update_password": "Update Password",
    "auth.error_credentials": "Invalid credentials.",
    "auth.error_passwords_match": "Passwords do not match.",
    "auth.error_generic": "Something went wrong. Please try again.",
    "personas.default": "Standard",
    "personas.default_desc": "Balanced and helpful",
    "personas.stoic": "Stoic",
    "personas.stoic_desc": "Calm and rational perspective",
    "personas.empathetic": "Empathetic",
    "personas.empathetic_desc": "Warm and supportive",
    "personas.analytical": "Analytical",
    "personas.analytical_desc": "Data-driven and objective",
    "settings.remove_avatar": "Remove Avatar",
    "settings.persona_default": "Standard",
    "settings.persona_default_desc": "Balanced and helpful",
    "settings.persona_stoic": "Stoic",
    "settings.persona_stoic_desc": "Calm and rational perspective",
    "settings.persona_empathetic": "Empathetic",
    "settings.persona_empathetic_desc": "Warm and supportive",
    "settings.persona_analytical": "Analytical",
    "settings.persona_analytical_desc": "Data-driven and objective",
    "pin.set_title": "Set your PIN",
    "pin.confirm_title": "Confirm your PIN",
    "pin.unlock_title": "Enter PIN to unlock",
    "pin.protected_desc": "Your data is protected",
  },
  ru: {
    "nav.dashboard": "Главная",
    "nav.journal": "Дневник",
    "nav.analysis": "Анализ",
    "nav.settings": "Настройки",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "dashboard.welcome": "С возвращением,",
    "dashboard.recent": "Последние анализы",
    "dashboard.stats": "Ваша статистика",
    "analysis.title": "Анализ эмоций",
    "analysis.placeholder": "Как вы себя чувствуете сегодня? Напишите свои мысли здесь...",
    "analysis.button": "Анализировать",
    "journal.title": "Ваш дневник",
    "journal.empty": "Записей пока нет. Начните с анализа первой мысли!",
    "settings.title": "Настройки",
    "settings.account_info": "Информация об аккаунте",
    "settings.edit": "Изм.",
    "settings.full_name": "Полное имя",
    "settings.language": "Язык",
    "settings.app_icon": "Иконка приложения",
    "settings.data_management": "Управление данными",
    "settings.export_data": "Экспорт данных",
    "settings.import_data": "Импорт данных",
    "settings.clear_data": "Очистить все данные",
    "settings.danger_zone": "Опасная зона",
    "settings.pin_code": "Замок по PIN-коду",
    "settings.set_pin": "Установить PIN",
    "settings.remove_pin": "Удалить PIN",
    "settings.reminder_time": "Ежедневное напоминание",
    "achievements.title": "Достижения",
    "calendar.title": "Эмоциональный календарь",
    "calendar.add_new": "Добавить событие",
    "calendar.event_name": "Название события",
    "calendar.empty": "Событий не запланировано.",
    "emotions.happy": "Счастье",
    "emotions.sad": "Грусть",
    "emotions.angry": "Гнев",
    "emotions.anxious": "Тревога",
    "emotions.neutral": "Нейтрально",
    "emotions.excited": "Восторг",
    "emotions.calm": "Спокойствие",
    "emotions.frustrated": "Разочарование",
    "journal.entries_count": "записей",
    "journal.filter_by": "Фильтр по",
    "journal.no_results": "Записей не найдено",
    "achievements.pioneer": "Первопроходец",
    "achievements.pioneer_desc": "Проанализируйте свою первую мысль.",
    "achievements.streak_7": "7 дней подряд",
    "achievements.streak_desc": "Сохраняйте серию в течение 7 дней.",
    "achievements.entry_30": "30 записей",
    "achievements.entry_30_desc": "Достигните 30 записей всего.",
    "achievements.entry_100": "100 записей",
    "achievements.entry_100_desc": "Достигните 100 записей всего.",
    "achievements.locked_desc": "Продолжайте, чтобы открыть!",
    "achievements.current_streak": "Текущая серия",
    "achievements.streak_sub": "Пишите каждый день, чтобы увеличить серию!",
    "achievements.unlocked": "Разблокировано",
    "settings.reminder_desc": "Получайте мягкое напоминание.",
    "settings.privacy": "Конфиденциальность",
    "settings.danger_zone_desc": "Это действие необратимо. Вся ваша история будет удалена.",
    "settings.general": "Общие",
    "settings.appearance": "Внешний вид",
    "settings.security": "Безопасность",
    "settings.data": "Данные",
    "settings.achievements": "Достижения",
    "settings.calendar": "Календарь",
    "settings.profile": "Профиль",
    "settings.account": "Аккаунт",
    "settings.persona": "AI Персона",
    "settings.persona_desc": "Выберите, как AI будет общаться с вами.",
    "settings.theme": "Тема",
    "settings.notifications": "Уведомления",
    "settings.reminder": "Ежедневное напоминание",
    "settings.pin_desc": "Защитите свои мысли 4-значным PIN-кодом.",
    "settings.biometrics": "Биометрическая разблокировка",
    "settings.export_desc": "Загрузите все свои записи в формате JSON.",
    "settings.edit_profile": "Редактировать профиль",
    "settings.save_changes": "Сохранить изменения",
    "settings.email_address": "Электронная почта",
    "settings.change_avatar": "Изменить аватар",
    "settings.streak_stats": "Статистика серии",
    "settings.total_entries": "Всего записей",
    "settings.unlocked_achievements": "Разблокировано",
    "settings.locked": "Заблокировано",
    "settings.add_event": "Добавить событие",
    "settings.event_title": "Название события",
    "settings.event_date": "Дата события",
    "settings.no_events": "Нет событий на этот день",
    "settings.your_achievements": "Ваши достижения",
    "settings.mental_calendar": "Ментальный календарь",
    "settings.voice_input_desc": "Используйте голос для записи мыслей.",
    "settings.voice_input_enabled": "Голосовой ввод включен",
    "settings.voice_input_disabled": "Голосовой ввод выключен",
    "settings.yes_delete": "Да, удалить всё",
    "settings.days": "Дней",
    "settings.progress": "Прогресс",
    "settings.disable_reminders": "Отключить напоминания",
    "journal.search_placeholder": "Поиск мыслей или тегов...",
    "journal.all_emotions": "Все эмоции",
    "journal.no_results_desc": "Попробуйте изменить фильтры или поисковый запрос.",
    "journal.intensity": "Интенсивность",
    "journal.details": "Подробнее",
    "analysis.input_source": "Источник ввода",
    "analysis.stop_recording": "Остановить запись",
    "analysis.voice_input": "Голосовой ввод",
    "analysis.detected_emotion": "Обнаруженная эмоция",
    "analysis.confidence": "Уверенность",
    "analysis.sentiment": "Настроение",
    "analysis.recommended_music": "Рекомендуемая музыка",
    "analysis.advice_title": "Душевный совет",
    "analysis.start_new": "Начать новый анализ",
    "analysis.ready_title": "Готовы к анализу?",
    "analysis.ready_desc": "Запишите свои мысли или используйте голосовой ввод, чтобы узнать свое эмоциональное состояние.",
    "dashboard.engine_online": "Эмоциональный движок онлайн",
    "dashboard.welcome_back": "С возвращением,",
    "dashboard.ready_question": "Готовы погрузиться в свои эмоции сегодня?",
    "dashboard.new_analysis": "Новый анализ",
    "dashboard.streak": "СЕРИЯ",
    "dashboard.total": "ВСЕГО",
    "dashboard.days": "Дней",
    "dashboard.keep_it_up": "Так держать!",
    "dashboard.total_entries": "Всего записей",
    "dashboard.mood": "НАСТРОЕНИЕ",
    "dashboard.dominant_mood": "Доминирующее настроение",
    "dashboard.level": "УРОВЕНЬ",
    "dashboard.level_label": "Уровень",
    "dashboard.to_next": "до следующего",
    "dashboard.distribution": "Распределение эмоций",
    "dashboard.unlock_desc": "Разблокируйте после 2+ записей",
    "dashboard.correlations": "Умные корреляции",
    "dashboard.correlations_desc": "Используйте теги в анализе, чтобы открыть корреляции.",
    "layout.light_mode": "Светлая тема",
    "layout.dark_mode": "Темная тема",
    "layout.logout": "Выйти",
    "sentiment.positive": "Позитивное",
    "sentiment.negative": "Негативное",
    "sentiment.neutral": "Нейтральное",
    "analysis.error_no_text": "Пожалуйста, введите текст",
    "analysis.error_failed": "Ошибка анализа. Пожалуйста, попробуйте еще раз.",
    "analysis.error_mic": "Микрофон не поддерживается",
    "analysis.error_voice": "Ошибка голосового ввода",
    "dashboard.no_data": "Нет данных",
    "settings.user_name": "Пользователь",
    "settings.no_email": "Email не указан",
    "settings.pin_active": "Активен и защищен",
    "settings.pin_not_set": "Не установлен - добавьте защиту",
    "auth.login_title": "Emotion Analyzer",
    "auth.login_subtitle": "Войдите, чтобы начать анализ эмоций",
    "auth.email": "Электронная почта",
    "auth.password": "Пароль",
    "auth.forgot_password": "Забыли пароль?",
    "auth.sign_in": "Войти",
    "auth.no_account": "Нет аккаунта?",
    "auth.sign_up": "Зарегистрироваться",
    "auth.signup_title": "Создать аккаунт",
    "auth.signup_subtitle": "Начните свое эмоциональное путешествие сегодня",
    "auth.full_name": "Полное имя",
    "auth.confirm_password": "Подтвердите пароль",
    "auth.have_account": "Уже есть аккаунт?",
    "auth.forgot_title": "Забыли пароль",
    "auth.forgot_subtitle": "Введите свой email, чтобы сбросить пароль",
    "auth.send_reset": "Отправить ссылку",
    "auth.back_to_login": "Вернуться к входу",
    "auth.reset_title": "Сброс пароля",
    "auth.reset_subtitle": "Введите новый пароль ниже",
    "auth.update_password": "Обновить пароль",
    "auth.error_credentials": "Неверные учетные данные.",
    "auth.error_passwords_match": "Пароли не совпадают.",
    "auth.error_generic": "Что-то пошло не так. Пожалуйста, попробуйте еще раз.",
    "personas.default": "Стандартный",
    "personas.default_desc": "Сбалансированный и полезный",
    "personas.stoic": "Стоик",
    "personas.stoic_desc": "Спокойная и рациональная перспектива",
    "personas.empathetic": "Эмпатичный",
    "personas.empathetic_desc": "Теплый и поддерживающий",
    "personas.analytical": "Аналитический",
    "personas.analytical_desc": "Объективный и основанный на данных",
    "settings.remove_avatar": "Удалить аватар",
    "settings.persona_default": "Стандартный",
    "settings.persona_default_desc": "Сбалансированный и полезный",
    "settings.persona_stoic": "Стоик",
    "settings.persona_stoic_desc": "Спокойная и рациональная перспектива",
    "settings.persona_empathetic": "Эмпатичный",
    "settings.persona_empathetic_desc": "Теплый и поддерживающий",
    "settings.persona_analytical": "Аналитический",
    "settings.persona_analytical_desc": "Объективный и основанный на данных",
    "pin.set_title": "Установите PIN-код",
    "pin.confirm_title": "Подтвердите PIN-код",
    "pin.unlock_title": "Введите PIN-код для разблокировки",
    "pin.protected_desc": "Ваши данные защищены",
  },
  kk: {
    "nav.dashboard": "Басты бет",
    "nav.journal": "Күнделік",
    "nav.analysis": "Талдау",
    "nav.settings": "Баптаулар",
    "common.save": "Сақтау",
    "common.cancel": "Бас тарту",
    "common.delete": "Жою",
    "dashboard.welcome": "Қош келдіңіз,",
    "dashboard.recent": "Соңғы талдаулар",
    "dashboard.stats": "Статистикаңыз",
    "analysis.title": "Эмоцияларды талдау",
    "analysis.placeholder": "Бүгін өзіңізді қалай сезінесіз? Ойларыңызды осында жазыңыз...",
    "analysis.button": "Талдау жасау",
    "journal.title": "Сіздің күнделігіңіз",
    "journal.empty": "Әзірге жазбалар жоқ. Алғашқы ойыңызды талдаудан бастаңыз!",
    "settings.title": "Баптаулар",
    "settings.account_info": "Аккаунт ақпараты",
    "settings.edit": "Өзгерту",
    "settings.full_name": "Толық аты-жөні",
    "settings.language": "Тіл",
    "settings.app_icon": "Қолданба белгішесі",
    "settings.data_management": "Деректерді басқару",
    "settings.export_data": "Деректерді экспорттау",
    "settings.import_data": "Деректерді импорттау",
    "settings.clear_data": "Барлық деректерді тазалау",
    "settings.danger_zone": "Қауіпті аймақ",
    "settings.pin_code": "PIN-код құлпы",
    "settings.set_pin": "PIN орнату",
    "settings.remove_pin": "PIN жою",
    "settings.reminder_time": "Күнделікті еске салғыш",
    "achievements.title": "Жетістіктер",
    "calendar.title": "Эмоционалды күнтізбе",
    "calendar.add_new": "Оқиға қосу",
    "calendar.event_name": "Оқиға атауы",
    "calendar.empty": "Жоспарланған оқиғалар жоқ.",
    "emotions.happy": "Қуаныш",
    "emotions.sad": "Мұң",
    "emotions.angry": "Ашу",
    "emotions.anxious": "Мазасыздық",
    "emotions.neutral": "Бейтарап",
    "emotions.excited": "Қобалжу",
    "emotions.calm": "Сабырлық",
    "emotions.frustrated": "Көңіл қалу",
    "journal.entries_count": "жазба",
    "journal.filter_by": "Сүзгілеу",
    "journal.no_results": "Жазбалар табылмады",
    "achievements.pioneer": "Пионер",
    "achievements.pioneer_desc": "Алғашқы ойыңызды талдаңыз.",
    "achievements.streak_7": "7 күндік серия",
    "achievements.streak_desc": "7 күн бойы серияны сақтаңыз.",
    "achievements.entry_30": "30 жазба",
    "achievements.entry_30_desc": "Барлығы 30 жазбаға жетіңіз.",
    "achievements.entry_100": "100 жазба",
    "achievements.entry_100_desc": "Барлығы 100 жазбаға жетіңіз.",
    "achievements.locked_desc": "Құлыпты ашу үшін жалғастырыңыз!",
    "achievements.current_streak": "Ағымдағы серия",
    "achievements.streak_sub": "Серияңызды арттыру үшін күн сайын жазыңыз!",
    "achievements.unlocked": "Ашылды",
    "settings.reminder_desc": "Жазу үшін жұмсақ ескерту алыңыз.",
    "settings.privacy": "Құпиялылық",
    "settings.danger_zone_desc": "Бұл әрекет қайтарылмайды. Барлық тарихыңыз жойылады.",
    "settings.general": "Жалпы",
    "settings.appearance": "Сыртқы түрі",
    "settings.security": "Қауіпсіздік",
    "settings.data": "Деректер",
    "settings.achievements": "Жетістіктер",
    "settings.calendar": "Күнтізбе",
    "settings.profile": "Профиль",
    "settings.account": "Аккаунт",
    "settings.persona": "AI кейіпкері",
    "settings.persona_desc": "AI сізбен қалай әрекеттесетінін таңдаңыз.",
    "settings.theme": "Тақырып",
    "settings.notifications": "Хабарландырулар",
    "settings.reminder": "Күнделікті еске салғыш",
    "settings.pin_desc": "Ойларыңызды 4 таңбалы PIN кодпен қорғаңыз.",
    "settings.biometrics": "Биометриялық құлыпты ашу",
    "settings.export_desc": "Барлық жазбаларыңызды JSON файлы ретінде жүктеп алыңыз.",
    "settings.edit_profile": "Профильді өңдеу",
    "settings.save_changes": "Өзгерістерді сақтау",
    "settings.email_address": "Электрондық пошта",
    "settings.change_avatar": "Аватарды өзгерту",
    "settings.streak_stats": "Серия статистикасы",
    "settings.total_entries": "Барлық жазбалар",
    "settings.unlocked_achievements": "Ашылған",
    "settings.locked": "Құлыпталған",
    "settings.add_event": "Оқиға қосу",
    "settings.event_title": "Оқиға атауы",
    "settings.event_date": "Оқиға күні",
    "settings.no_events": "Бұл күнге оқиғалар жоқ",
    "settings.your_achievements": "Сіздің жетістіктеріңіз",
    "settings.mental_calendar": "Психикалық күнтізбе",
    "settings.voice_input_desc": "Ойларды жазу үшін дауысыңызды пайдаланыңыз.",
    "settings.voice_input_enabled": "Дауыспен енгізу қосулы",
    "settings.voice_input_disabled": "Дауыспен енгізу өшірулі",
    "settings.yes_delete": "Иә, бәрін жою",
    "settings.days": "Күн",
    "settings.progress": "Прогресс",
    "settings.disable_reminders": "Еске салғыштарды өшіру",
    "journal.search_placeholder": "Ойларды немесе тегтерді іздеу...",
    "journal.all_emotions": "Барлық эмоциялар",
    "journal.no_results_desc": "Сүзгілерді немесе іздеу сұрауын өзгертіп көріңіз.",
    "journal.intensity": "Қарқындылық",
    "journal.details": "Толығырақ",
    "analysis.input_source": "Енгізу көзі",
    "analysis.stop_recording": "Жазуды тоқтату",
    "analysis.voice_input": "Дауыспен енгізу",
    "analysis.detected_emotion": "Анықталған эмоция",
    "analysis.confidence": "Сенімділік",
    "analysis.sentiment": "Көңіл-күй",
    "analysis.recommended_music": "Ұсынылған музыка",
    "analysis.advice_title": "Жанға жайлы кеңес",
    "analysis.start_new": "Жаңа талдауды бастау",
    "analysis.ready_title": "Талдауға дайынсыз ба?",
    "analysis.ready_desc": "Эмоционалды күйіңізді білу үшін ойларыңызды жазыңыз немесе дауыспен енгізуді пайдаланыңыз.",
    "dashboard.engine_online": "Эмоционалды қозғалтқыш қосулы",
    "dashboard.welcome_back": "Қош келдіңіз,",
    "dashboard.ready_question": "Бүгін эмоцияларыңызға үңілуге дайынсыз ба?",
    "dashboard.new_analysis": "Жаңа талдау",
    "dashboard.streak": "СЕРИЯ",
    "dashboard.total": "БАРЛЫҒЫ",
    "dashboard.days": "Күн",
    "dashboard.keep_it_up": "Осылай жалғастыра беріңіз!",
    "dashboard.total_entries": "Барлық жазбалар",
    "dashboard.mood": "КӨҢІЛ-КҮЙ",
    "dashboard.dominant_mood": "Басым көңіл-күй",
    "dashboard.level": "ДЕҢГЕЙ",
    "dashboard.level_label": "Деңгей",
    "dashboard.to_next": "келесіге дейін",
    "dashboard.distribution": "Эмоциялардың таралуы",
    "dashboard.unlock_desc": "2+ жазбадан кейін ашылады",
    "dashboard.correlations": "Ақылды корреляциялар",
    "dashboard.correlations_desc": "Корреляцияларды ашу үшін талдауда тегтерді пайдаланыңыз.",
    "layout.light_mode": "Жарық режим",
    "layout.dark_mode": "Қараңғы режим",
    "layout.logout": "Шығу",
    "sentiment.positive": "Оң",
    "sentiment.negative": "Теріс",
    "sentiment.neutral": "Бейтарап",
    "analysis.error_no_text": "Мәтінді енгізіңіз",
    "analysis.error_failed": "Талдау сәтсіз аяқталды. Қайталап көріңіз.",
    "analysis.error_mic": "Микрофонға қолдау көрсетілмейді",
    "analysis.error_voice": "Дауыспен енгізу қатесі",
    "dashboard.no_data": "Деректер жоқ",
    "settings.user_name": "Пайдаланушы",
    "settings.no_email": "Email көрсетілмеген",
    "settings.pin_active": "Белсенді және қауіпсіз",
    "settings.pin_not_set": "Орнатылмаған - қорғаныс қосыңыз",
    "auth.login_title": "Emotion Analyzer",
    "auth.login_subtitle": "Эмоцияларды талдауды бастау үшін кіріңіз",
    "auth.email": "Электрондық пошта",
    "auth.password": "Құпия сөз",
    "auth.forgot_password": "Құпия сөзді ұмыттыңыз ба?",
    "auth.sign_in": "Кіру",
    "auth.no_account": "Аккаунтыңыз жоқ па?",
    "auth.sign_up": "Тіркелу",
    "auth.signup_title": "Аккаунт жасау",
    "auth.signup_subtitle": "Эмоционалды саяхатыңызды бүгін бастаңыз",
    "auth.full_name": "Толық аты-жөні",
    "auth.confirm_password": "Құпия сөзді растаңыз",
    "auth.have_account": "Аккаунтыңыз бар ма?",
    "auth.forgot_title": "Құпия сөзді ұмыттыңыз ба?",
    "auth.forgot_subtitle": "Құпия сөзді қалпына келтіру үшін электрондық поштаңызды енгізіңіз",
    "auth.send_reset": "Сілтемені жіберу",
    "auth.back_to_login": "Кіруге оралу",
    "auth.reset_title": "Құпия сөзді қалпына келтіру",
    "auth.reset_subtitle": "Төменде жаңа құпия сөзді енгізіңіз",
    "auth.update_password": "Құпия сөзді жаңарту",
    "auth.error_credentials": "Жарамсыз деректер.",
    "auth.error_passwords_match": "Құпия сөздер сәйкес келмейді.",
    "auth.error_generic": "Бірдеңе дұрыс болмады. Қайталап көріңіз.",
    "personas.default": "Стандартты",
    "personas.default_desc": "Теңгерімді және пайдалы",
    "personas.stoic": "Стоик",
    "personas.stoic_desc": "Сабырлы және ұтымды көзқарас",
    "personas.empathetic": "Эмпатикалық",
    "personas.empathetic_desc": "Жылы және қолдаушы",
    "personas.analytical": "Аналитикалық",
    "personas.analytical_desc": "Деректерге негізделген және объективті",
    "settings.remove_avatar": "Аватарды жою",
    "settings.persona_default": "Стандартты",
    "settings.persona_default_desc": "Теңгерімді және пайдалы",
    "settings.persona_stoic": "Стоик",
    "settings.persona_stoic_desc": "Сабырлы және ұтымды көзқарас",
    "settings.persona_empathetic": "Эмпатикалық",
    "settings.persona_empathetic_desc": "Жылы және қолдаушы",
    "settings.persona_analytical": "Аналитикалық",
    "settings.persona_analytical_desc": "Деректерге негізделген және объективті",
    "pin.set_title": "PIN-кодты орнатыңыз",
    "pin.confirm_title": "PIN-кодты растаңыз",
    "pin.unlock_title": "Құлыпты ашу үшін PIN-кодты енгізіңіз",
    "pin.protected_desc": "Сіздің деректеріңіз қорғалған",
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguageAndPersist = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageAndPersist, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
